apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-1
  name: web-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-1
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
